[[plugins]]
repo = 'cocopon/iceberg.vim.git'

[[plugins]]
repo = 'Shougo/unite.vim.git'

[[plugins]]
repo = 'Shougo/vimfiler.vim.git'

[[plugins]]
repo = 'vim-airline/vim-airline.git'

[[plugins]]
repo = 'vim-airline/vim-airline-themes.git'

[[plugins]]
repo = 'LeafCage/vimhelpgenerator.git'
